# Generated by Django 3.0.5 on 2021-02-28 14:33

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to=myapp.models.user_directory_path)),
            ],
        ),
    ]
